default_language_version:
  python: python3.8
exclude: reports
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.1
    hooks:
    - id: reorder-python-imports
      args: [--py37-plus]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    - id: flake8
      args: [--config=.flake8]
      additional_dependencies:
        - flake8-builtins==1.4.1
        - flake8-comprehensions==2.1.0
        - flake8-bugbear==19.3.0
        - flake8-eradicate==0.2.1
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [-S]
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
